intel/libva-utils

putsurface/Makefile.am
fixes #9
Signed-off-by: Sean V Kelley <seanvk@posteo.de>
=> putsurface: Enable putsurface bins according to flags

configure.ac, test/Makefile.am
This pull request fixes two issues found during QA Testing for 1.8.0.pre1.  This should trigger a 1.8.0.pre2 release and patches will be cherry picked.
=> Fixing issues found on the QA testing for 1.8.0.pre1 pre-release tarball

encode/avcenc.c
Fixes #32
Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>
=> ENC: add AUD NAL unit at the beginning of pic

encode/avcenc.c
this fix the R2R issue with AVC encoder
=> better Quality with direct_spatial_mv_pred_flag=1

encode/avcenc.c
Fixes #37
Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>
=> add the frame number as the cmd line input parameter

.travis.yml, test/Makefile.am
Fixes compilation error for GCC 6.x
Fixes libva dependency for Travis CI
=> Fix GCC 6.x and Travis Compilation Failures

test/test_va_api_fixture.cpp, test/test_va_api_init_terminate.cpp
Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>
=> Fixes #52: add explicit braces to avoid 'ambiguous else' warning.

configure.ac
Fixes #41
Signed-off-by: Lim Siew Hoon <siew.hoon.lim@intel.com>
=> Fix to retrieve libva version.

configure.ac, videoprocess/Makefile.am, videoprocess/process.cfg.template, videoprocess/vavpp.cpp
This test case was added on the removed libva staging branch a few year ago, I added it back to libva-utils
=> Add video process test case

encode/Makefile.am, encode/vp9enc.c
Signed-off-by: peng.chen <peng.c.chen@intel.com>
=> Add vp9enc tool for testing driver

vainfo/vainfo.c
Depends on: https://github.com/01org/libva/pull/117
=> vainfo: Use new va*Str() functions

Android.mk, decode/Android.mk, encode/Android.mk, putsurface/putsurface_android.cpp, putsurface/putsurface_common.c, vainfo/Android.mk, vainfo/vainfo.c, videoprocess/Android.mk, videoprocess/vavpp.cpp
Add new Android.mk in the top source directory and some sub-directories,
update some existent Android.mk files. Then I fixed compilation errors
=> Build libva-utils on Android

test/test_va_api_fixture.cpp, test/test_va_api_fixture.h, test/test_va_api_init_terminate.cpp, test/test_va_api_query_vendor.cpp
Various fixes to allow user-defined driver in tests.
=> Tests: Allow user to specify driver for test execution

common/va_display.c, decode/tinyjpeg.c, encode/avcenc.c, encode/jpegenc.c, encode/svctenc.c, vainfo/vainfo.c
Trying to avoid regressions while removing some warnings. Just a few more to have a clean build with -Wall enabled
=> Misc cleanup

test/test.h, test/test_data.h, test/test_streamable.h, test/test_va_api_fixture.h
Ensure all test headers have a header guard and that each guard is unique.
=> test: fix header guards

test/Makefile.am, test/test_data.h, test/test_internal.cpp, test/test_utils.h, test/test_va_api_createbuffer.cpp, test/test_va_api_createcontext.cpp, test/test_va_api_createsurfaces.cpp, test/test_va_api_fixture.cpp, test/test_va_api_fixture.h
=> Define and use Resolution data structure

encode/vp9enc.c
The patch series adds support for vp9 low power encoding and fixes a bitrate issue for VBR
=> Patches for vp9enc

decode/loadjpeg.c
Check the return value to fix build warning.
Signed-off-by: Jun Zhao <jun.zhao@intel.com>
=> decode/loadjpeg: Add return value check for fread.

test/test_va_api_createbuffer.cpp
this add the minium resolution check in the unit test
Fixes #88
Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>
=> fix the regression of unit test

test/test_data.h, test/test_va_api_config_attribs.cpp, test/test_va_api_createbuffer.cpp, test/test_va_api_createcontext.cpp, test/test_va_api_createsurfaces.cpp, test/test_va_api_display_attribs.cpp, test/test_va_api_fixture.cpp, test/test_va_api_fixture.h, test/test_va_api_get_create_config.cpp, test/test_va_api_get_max_values.cpp, test/test_va_api_query_config.cpp
Fixes #89 
Fixes #96 
Fixes #99
=> Various test bug fixes

test/test_va_api_get_create_config.cpp
Driver should allow 0x0 (i.e. VA_ENC_PACKED_HEADER_NONE) value
for the VAConfigAttribEncPackedHeaders attribute during
vaCreateConfig when the attribute is supported.
This test supercedes intel/intel-vaapi-driver#361
Also see intel/intel-vaapi-driver#358 and intel/libva#178
=> test/get_create_config: test for packed headers special case

common/meson.build, decode/meson.build, encode/meson.build, meson.build, meson_options.txt, putsurface/meson.build, test/meson.build, vainfo/meson.build, videoprocess/meson.build
I enjoyed building libva/intel-vaapi-driver with meson, so why not the utils?
=> add meson build

common/va_display.c, common/va_display_android.cpp, decode/Android.mk, encode/Android.mk, vainfo/Android.mk, videoprocess/Android.mk
Signed-off-by: tiantian <tiantian.wang@intel.com>
=> add vainfo support in android

common/loadsurface.h, decode/Makefile.am, decode/tinyjpeg.c, encode/Makefile.am, encode/h264encode.c, putsurface/Makefile.am, vainfo/Makefile.am, videoprocess/Makefile.am, videoprocess/vavpp.cpp
In attion, this fixes all warnings reported by -Wall
=> Add '-Wall' or '-fstack-protector' compilation flags

configure.ac, vendor/intel/Makefile.am, vendor/intel/avcstreamoutdemo.c, vendor/intel/avcstreamoutdemo.h
Add new folder 'vendor/intel' and give sample code for how to use avc streamout
Signed-off-by: Zhengguo.Xu <zhengguo.xu@intel.com>
=> Add sample code for avc decode streamout

encode/Makefile.am, encode/hevcencode.c
This files is  an example tool to encode HEVC.
=> H265sample

videoprocess/Makefile.am, videoprocess/process_chromasitting.cfg.template, videoprocess/process_denoise.cfg.template, videoprocess/process_scaling_csc.cfg.template, videoprocess/process_sharpness.cfg.template, videoprocess/vppchromasitting.cpp, videoprocess/vppdenoise.cpp, videoprocess/vppscaling_csc.cpp, videoprocess/vppsharpness.cpp
Signed-off-by: kelly-du <kelly.du@intel.com>
=> add VP sample for scaling,csc,sharpness,denoise,chromasitting.

videoprocess/Makefile.am, videoprocess/process_blending.cfg.template, videoprocess/vppblending.cpp
Signed-off-by: kelly-du <kelly.du@intel.com>
=> add VP sample for Blending.

videoprocess/vavpp.cpp
This patch adds support for CSC with AYUV format in vavpp
=> vavpp: csc with AYUV format

NEWS
Signed-off-by: intel <carl.zhang@intel.com>
=> unify NEWS format

videoprocess/Makefile.am, videoprocess/process_scaling_n_out_usrptr.cfg.template, videoprocess/vppscaling_n_out_usrptr.cpp
Signed-off-by: kelly-du <kelly.du@intel.com>
=> add VP sample for usrptr and 1:N output

videoprocess/README.md
Signed-off-by: kelly-du <kelly.du@intel.com>
=> add the VP samples README.

vainfo/vainfo.c
usage: vainfo -a
Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>
=> Added displaying supported config attributes

test/test_streamable.h, test/test_va_api_createsurfaces.cpp
These scoped traces will help with debugging failures.
=> Test: Add some scoped traces

encode/meson.build, meson.build, vendor/intel/meson.build, vendor/intel/sfcsample/meson.build, videoprocess/meson.build
=> Add missing samples to Meson build

NEWS
Signed-off-by: Carl Zhang <carl.zhang@intel.com>
=> update NEWS for 2.8.0

encode/hevcencode.c, encode/jpegenc.c, encode/mpeg2vaenc.c, encode/vp8enc.c, putsurface/putsurface_common.c, vendor/intel/sfcsample/VDecAccelVA.cpp, vendor/intel/sfcsample/VDecAccelVA.h, videoprocess/vppscaling_n_out_usrptr.cpp
Signed-off-by: Tianhao Liu <tianhao.liu@intel.com>
=> Fix KW issues

encode/hevcencode.c
Signed-off-by: Shawn Li <shawn.li@intel.com>
=> Fix one KW issue

encode/hevcencode.c
Signed-off-by: Shawn Li <shawn.li@intel.com>
=> fix one null pointer dereference risk

encode/vp8enc.c
This addresses https://github.com/intel/libva-utils/issues/209.
=> Add support for a --repeat command line option to vp8enc.

test/test_data.h
Signed-off-by: Shawn Li <shawn.li@intel.com>
=> Enable new caps for rate control

videoprocess/Makefile.am, videoprocess/process_va_copy.cfg.template, videoprocess/vacopy.cpp
add mediaCopy sample code.
linked libva PR: https://github.com/intel/libva/pull/243
linked media_driver PR:https://github.com/intel/media-driver/pull/1070
=> add Mediacopy Sample code

.github/workflows/freebsd.yml, .github/workflows/ubuntu.yml
Example of actions run: https://github.com/dvrogozh/libva-utils/runs/1698640648. They won't be active till we will merge in the change.
=> ci: enable github actions

.github/workflows/freebsd.yml
Fixes https://github.com/intel/libva-utils/issues/227
=> CI: upgrade freebsd-vm to 12.2

encode/h264encode.c
h264encode utility fails to run on the platforms where only low-power
(VAEntrypointEncSliceLP) entry points are supported . This change adds
a low_power command line option
=> h264encode : Added low_power command line option

vainfo/vainfo.c
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>
=> vainfo: add VA_RC_TCBRC to reported caps list

encode/jpegenc.c
add check of malloc result for jpegenc
=> add check of malloc result for jpegenc

.github/workflows/freebsd.yml
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>
=> ci: fix freebsd build by switching to vmactions/freebsd-vm@v0.1.3

videoprocess/Makefile.am, videoprocess/process_3dlut.cfg.template, videoprocess/vpp3dlut.cpp
Signed-off-by: Furong Zhang <furong.zhang@intel.com>
=> Added 3DLUT sample code and configuration file.

videoprocess/vavpp.cpp
Signed-off-by: Furong Zhang <furong.zhang@intel.com>
=> Added Planar BGR support.

videoprocess/Makefile.am, videoprocess/process_hdr_tm_h2h.cfg.template, videoprocess/process_hdr_tm_h2s.cfg.template, videoprocess/vpphdr_tm.cpp
Signed-off-by: Furong Zhang <furong.zhang@intel.com>
=> Added HDR10 Tone Mapping sample code including H2H and H2S config files.

videoprocess/vpphdr_tm.cpp
fix hdr local variable pointer access issue
local variable will be freed after return, so need the
caller to convey it
Signed-off-by: caij <jianxing.cai@intel.com>
=> fix hdr issue

encode/hevcencode.c
Set correct entrypoint to VAEntrypointEncSliceLP for HEVC lowpower
insead of VAEntrypointEncSlice
=> [Encode] Set correct entrypoint for lowpower

configure.ac, meson.build
Signed-off-by: Carl Zhang <carl.zhang@intel.com>
=> libva-utils 2.16.0.pre1

encode/Makefile.am, encode/av1encode.c, encode/meson.build
=> Add av1 encode sample code

encode/av1encode.c
=> Fix possible memory leak

common/va_display_drm.c
Signed-off-by: Sil Vilerino <sivileri@microsoft.com>
Related https://github.com/intel/libva/pull/688
=> va_display_drm: Allow VGEM for WSL2

decode/tinyjpeg.c
Signed-off-by: Wu, Stella <stella.wu@intel.com>
=> Add Scan Num limitation

test/test_data.h
see https://github.com/intel/libva/pull/664
Signed-off-by: jianfeng.zheng <jianfeng.zheng@mthreads.com>
=> test: add VAProfileH264High10

decode/tinyjpeg.c
Signed-off-by: Wu, Stella <stella.wu@intel.com>
=> Add Th limitation by HUFFMAN_TABLES Count

README.md
Add detail steps for libva-utils
=> Add build and install libva-utils steps

decode/tinyjpeg.c
fix scan num limitation.
Signed-off-by: caij jianxing.cai@intel.com
=> fix scan num limitation

encode/hevcencode.c
=> Revert "[Encode] Add support for VAConfigAttribEncHEVCBlockSizes & VAConfigAttribEncHEVCFeatures"

encode/hevcencode.c
Set corresponding parameters in SPS etc. to the values from these 2 attributes, instead of hard-coding. If the attributes are not set, use default values which remains unchanged.
=> [Encode] Add support for VAConfigAttribEncHEVCBlockSizes & VAConfigAttribEncHEVCFeatures

encode/av1encode.c
This PR add support to allow user select entrypoint between VAEntrypointEncSlice and VAEntrypointEncSliceLP.
=> [AV1e] allow user select entrypoint for av1 encoder

NEWS
it should be 2.20 instead of 2.2020
=> fix: fix typo of version in NEWS

decode/loadjpeg.c, decode/tinyjpeg.c
Signed-off-by: Pengxin Yuan <pengxin.yuan@intel.com>
=> Fix some coverity issues exposed in decode

test/test_data.h, test/test_va_api_createsurfaces.cpp
Signed-off-by: Li, Xin6 <xin6.li@intel.com>
=> Add Prime3 memtype support

.github/workflows/ubuntu.yml, .github/workflows/windows.yml
=> workflow: add workflow permission for all jobs

.github/workflows/freebsd.yml
=> ci: harden permission for freebsd.yml

.github/workflows/freebsd.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
using read-all access for all of the available scopes
=> ci:correct the permission of workflows
