test/Makefile.am
test/test_streamable.h
test/test_va_api_fixture.h

When gtest prints out test params (e.g. --gtest_list_tests)
for VAProfile and VAEntrypoint, it prints the value.  This
makes it difficult to know which profile/entrypoint it
actually is without cross-referencing the va header manually.
This patch adds output stream operators for VAProfile and
VAEntrypoint to print out the name along with its value.  GTest
will automatically use these operators to print profile/entrypoint
params in its test output.

test: add stream operators for VAProfile and VAEntrypoint

---

Makefile.am
README.md
configure.ac

libva-utils contains utilities and example applications to
use VA-API.
--enable-tests configure flag enables a suite of unit tests
that are based on Google Test Framework
The flag name is modified to keep consistency with intel-vaapi-driver
unit tests configuration flag
Fixes:#12
Signed-off-by: Daniel Charles <daniel.charles@intel.com>

enable-tests: normalize configure flag name

---

configure.ac

driver path is obtained from libva.pc.  If not found a warning
is given for user to export driver folder location
On the summary the driver folder will be shown if installed or
repeat the warning otherwise
Fixes #15
Signed-off-by: Daniel Charles <daniel.charles@intel.com>

configure: warn user if driver path is not found

---

common/Makefile.am
test/Makefile.am

This fixes https://github.com/01org/libva-utils/issues/26

Add the missing files to EXTRA_DIST

---

configure.ac

This was a leftover from libva split, there are probably
many others uneeded content to remove from configure.ac
fedora-review complain on this old macro - rhbz#1437937
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

libva-utils: Remove AC_PROG_LIBTOOL leftover

---

putsurface/putsurface_wayland.c

putsurface_wayland is a wayland client and should not include
the wayland-server.h header file.  Instead, include the
wayland-client.h header instead.
Fixes #34

putsurface: include wayland-client.h instead of wayland-server.h

---

putsurface/putsurface_wayland.c

Otherwise thread1 will dereference a NULL pointer

putsurface_wayland: fix segmentation fault in multithreads

---

configure.ac

This is needed once the libva library name is change to libva-2.0

Replace libva with libva-2.0

---

common/va_display.c
common/va_display.h
common/va_display_drm.c
vainfo/vainfo.c

3 commits
* add '--device' option to specify device name if the current display is drm.
* add '--help' option to show available options 
* replace abort() with exit(1)

Some enhancements to vainfo

---

encode/avcenc.c

This patch will be required once the typo is fixed libva 2.0.0

Fix a typo in VAConfigAttribValEncROI

---

encode/avcenc.c
encode/h264encode.c
encode/svctenc.c
test/Makefile.am
test/test_data.h
test/test_streamable.h
vainfo/vainfo.c

enums marked as deprecated should not be used any more.

Fix deprecated warning

---

vainfo/vainfo.c

Otherwise lots of profile/entrypoint pairs are not output

Entrypoint index should start from 0

---

.travis.yml

libva-utils v1.8-branch doesn't work with libva master any more
DO NOT MERGE to master branch!!!

travis: clone libva v1.8-branch to build libva-utils v1.8-branch

---

test/test_streamable.h

New vaStr methods were added in libva 2.0.
Fixes #62

test/streamables: use vaStr methods

---

test/test_va_api_fixture.cpp

Don't expect vaMaxNumConfigAttributes to be 32.
vaMaxNumConfigAttributes result is defined by the driver
implementation and may not be the same for all drivers.

test: vaMaxNumConfigAttributes is implementation specific

---

test/test.h
test/test_va_api_display_attribs.cpp
test/test_va_api_fixture.cpp
test/test_va_api_init_terminate.cpp
test/test_va_api_query_config.cpp

Add convenience macros to improve VAStatus logging and other checks.  Also, make sure the order of parameters to test macros are correct.  That is, expected value should be first parameter and actual value should be second parameter
BEFORE:
```
test_va_api_fixture.cpp:503: Failure
Expected: vaStatus
Which is: 12
To be equal to: error
Which is: 13
```
AFTER:
```
test_va_api_fixture.cpp:504: Failure
Expected: VaapiStatus(error)
Which is: VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT
To be equal to: VaapiStatus(vaStatus)
Which is: VA_STATUS_ERROR_UNSUPPORTED_PROFILE
```

Improve test output logging

---

test/test_streamable.h
test/test_va_api_createbuffer.cpp
test/test_va_api_createbuffer.h

Split each buffer type into it's own test and
make the test params streamable so that test logs
are more useful.
Before:
```
CreateBufferWithOutData/0  # GetParam() = 32-byte object <...
...
```
After:
```
CreateBufferWithOutData/0  # GetParam() = 0:VAProfileMPEG2Simple,1:VAEntrypointVLD,0:VAPictureParameterBufferType
...
```

test: improve create_buffer test logging

---

.travis.yml
CONTRIBUTING.md
INSTALL
README.md
configure.ac

We moved libva from github/01org to github/intel, however some files
still have links to the old 01org URLs, this commit updates these
links to the new intel URLs. In addition, this commit added a contact
email address for security issue reporting
https://github.com/intel/libva-utils/issues/103

Use the new link URLs

---

test/test_va_api_init_terminate.cpp
test/test_va_api_query_vendor.cpp

Conformance tests should be as generic as possible and
not assume availability of any specific driver.
Fixes #93
Fixes #94
Fixes #95

test: remove i965 driver specific cases

---

encode/Makefile.am
encode/meson.build
encode/vp8enc.c

The application was tested against following example videos:
taken from https://media.xiph.org/video/derf/ and converted to yuv420p with ffmpeg
akiyo_w352_h288_f300_fps30.yuv
crosswalk_w4096_h2160_f300_fps60.yuv
football_w720_h486_f360_fps30.yuv
stockholm_w1280_h720_f604_fps60.yuv
tractor_w1920_h1080_f690_fps25.yuv
CQP, CBR, VBR modes in combination with 1,2,3 temporal layers were tested.
Videos with 2 or 3 temporal layer were reduced to 1 and 2 temporal layers. (with vp8halfrate)
The scripts for running the test can be found here: 
https://github.com/ottingerg/libva-utils/tree/master/encode/test
Encoded videos were manually visually checked. There are some issues with pink artefacts with fast moving objects on videos encoded with 2 or 3 temporal layers in combination with CBR or VBR …

vp8enc: add application for VP8 and basic VP8 SVCT encoding (part of GSOC2018)

---

vendor/intel/Makefile.am
vendor/intel/sfcsample/Makefile.am

Otherwise the package made by 'make dist' fails to build with similar
errors below:
CC       avcstreamoutdemo.o
avcstreamoutdemo.c:46:10: fatal error: avcstreamoutdemo.h: No such file
or directory
#include "avcstreamoutdemo.h"
^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:456: recipe for target 'avcstreamoutdemo.o' failed
make[1]: *** [avcstreamoutdemo.o] Error 1

Include .h for extra dist

---

videoprocess/vavpp.cpp

The frame format should be BGRA.

vavpp: requires BGRA frame when saving a BGRA file

---

configure.ac
decode/Makefile.am
encode/Makefile.am
putsurface/Makefile.am
vainfo/Makefile.am
videoprocess/Makefile.am

Not all toolchains provide support for -fstack-protector. This patch
provides a configure check to avoid build errors like
/home/buildroot/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/6.4.0/../../../../x86_64-buildroot-linux-uclibc/bin/ld: cannot find -lssp_nonshared
/home/buildroot/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/6.4.0/../../../../x86_64-buildroot-linux-uclibc/bin/ld: cannot find -lssp

Check for -fstack-protector

---

encode/meson.build

h264enc collides with the h264enc binary installed by openh264 and the
autotools based build names the binary h264encode.

meson: rename the h264enc binary to be in line with the autotools build

---

test/test_data.h

Fix VaCreatconfig attribute check fail issue caused by missing two ratecontrol bitmasks.
Signed-off-by: Shawn Li <shawn.li@intel.com>

Align libva attribute check 

---

videoprocess/vppscaling_n_out_usrptr.cpp

When updating libva-utils from 2.4.0 to 2.6.0 in Chrome OS I bumped into
the following error:
```
portage/media-video/libva-utils-2.6.0-r1/work/libva-utils-2.6.0/videoprocess/vppscaling_n_out_usrptr.cpp:41:10: fatal error:
'va/va_x11.h' file not found
```
Signed-off-by: Edward Baker <edward.baker@intel.com>

Ifdef va_x11 in VP sample for usrptr

---

configure.ac
decode/Android.mk
encode/Android.mk
meson.build
vainfo/Android.mk
vendor/intel/sfcsample/VDecAccelVA.cpp
videoprocess/Android.mk

Meson adds `-Wl,--as-needed` by default, see https://github.com/mesonbuild/meson/commit/58ca96994f5a
From [build log](https://github.com/intel/libva-utils/files/4004198/libva-utils-2.6.0.log):
```
=>> Checking shared library dependencies
0x00000001 NEEDED               Shared library: [libX11.so.6]
0x00000001 NEEDED               Shared library: [libc++.so.1]
0x00000001 NEEDED               Shared library: [libc.so.7]
0x00000001 NEEDED               Shared library: [libcxxrt.so.1]
0x00000001 NEEDED               Shared library: [libgcc_s.so.1]
0x00000001 NEEDED               Shared library: [libm.so.5]
0x00000001 NEEDED               Shared library: [libthr.so.3]
0x00000001 NEEDED               Shared library: [libva-drm.so.2]
0x00000001 NEEDED               Shared library: …
```

Drop unused dependencies

---

encode/jpegenc.c

Such a frame takes 12 MiB in YUV, which is bigger than the stack size of most operating systems.
Instead of allocating the buffer on the stack, use `malloc()`.
Signed-off-by: Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>

jpegenc: Allow encoding a 4K frame

---

test/test_va_api_init_terminate.cpp

it is used to fix such issue, version from libva-utils and libva is different.
because older libva-utils should also work with newer libva.
Signed-off-by: Carl Zhang <carl.zhang@intel.com>

remove version check for test vaInitialize_vaTerminate

---

encode/h264encode.c
encode/hevcencode.c

When used with for instance 4K UHD  (-h 2160 -w 3840) h264encode and
hevcencode `codebuf_size` computation was wrong due to overflow and lead to
"setup_encode:vaCreateBuffer (1349) failed,exit" error
Also fix the frame_bitrate integer overflow

h264encode, hevcencode: fix integer overflow for high definition

---

.github/workflows/freebsd.yml

Switching to:
* vmactions/freebsd-vm@v0.1.5 to fetch FreeBSD 13
* macos-10.15
It seems github systems are getting updates with later macos
versions (11.6.1) which don't have vboxmanage required to run VMs.
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

ci: fix freebsd build

---

common/Makefile.am
common/va_display_drm.c
configure.ac
meson.build

call drm function to avoid invalid node
check the name of vgem
Signed-off-by: Carl Zhang <carl.zhang@intel.com>

exclude vgem node and invalid drm node in vainfo

---

decode/tinyjpeg-internal.h
decode/tinyjpeg.c

jpeg components number should not exceed 4 following the spec
Signed-off-by: Liu, Chuan1 <chuan1.liu@intel.com>

[Decode] Components exceed the value specified by Jpeg spec

---

meson.build

The pkgconfig file is named 'libdrm', as can be seen in configure.ac,
not 'drm'.
Fixes: bfb6b98 ("exclude vgem node and invalid drm node in vainfo")
Cc: @XinfengZhang

meson: Search for libdrm

---

vainfo/vainfo.c

Add missing letter. Actually, it should've been "**a**rithm**e**tic coding", not "**a**rithm**a**tic coding", but it's leaked to public API, so left unfixed.

Fix trivial typo in vainfo

---

videoprocess/vpphdr_tm.cpp

null check for vpphdr buffer ptr
null check for vpphdr buffer ptr
Signed-off-by: caij jianxing.cai@intel.com

null check for vpphdr buffer ptr

---

encode/meson.build
meson.build

In Gentoo we allow disabling the tools and putsuface separately, so
moving the threads check out of the encode subdirectory helps.
Cc: @XinfengZhang

meson: Search for threads in top-level meson.build

---

meson.build

Bump the required version to 0.53.0 - it's available on Debian
old-stable (buster-backports), Ubuntu 20.04 (focal) and newer distros.
This allows us to use the summary() feature, similar to the autotools
one.

produce summary() when 0.53.0 is present

---

common/va_display.c

Currently we silently fall-though all possible display types. Which is
fairly confusing for the end user if `vainfo` works but it fails on
their favourite program.
Add an explicit print, saving time to both users and developers.

common: print the display being attempted

---

videoprocess/meson.build

The vacopy vpp3dlut vpphdr_tm tools are available in autotools but are missing with meson. Add them
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

meson: add missing tools

---

vainfo/vainfo.c

Fix typo in `show_config_attributes` that was printing the wrong value for `VAConfigAttribEncMaxSlices`

Fix reporting of VAConfigAttribEncMaxSlices in vainfo -a

---

.github/workflows/EnterDevShell.ps1
.github/workflows/windows.yml
common/meson.build
common/va_display.c
common/va_display_win32.c
getopt/getopt.h
getopt/getopt_long.c
getopt/meson.build
meson.build
meson_options.txt
test/compat_win32.h
test/meson.build
test/test_utils.h
test/test_va_api_config_attribs.cpp
test/test_va_api_createbuffer.cpp
test/test_va_api_createcontext.cpp
test/test_va_api_createsurfaces.cpp
test/test_va_api_display_attribs.cpp
test/test_va_api_fixture.cpp
test/test_va_api_fixture.h
test/test_va_api_get_create_config.cpp
test/test_va_api_init_terminate.cpp
vainfo/vainfo.c

This MR ports vainfo and the gtest suite for Windows using libva-win32 
Requires: https://github.com/intel/libva/pull/621

Port vainfo and tests for libva-win32

---

encode/av1encode.c

fix coding issues in av1e sample code
1. function return type
2. ref_frame_idx idx too large

fix coding issue

---

videoprocess/process_hdr_tm_h2h.cfg.template
videoprocess/process_hdr_tm_h2s.cfg.template
videoprocess/vpphdr_tm.cpp

VAAPI defines the maximum display luminance as in the unit of 0.0001nits.
Signed-off-by: Furong Zhang <furong.zhang@intel.com>

Correct maximum display luminance per VAAPI definition.

---

common/Makefile.am
configure.ac
test/test_va_api_fixture.cpp

Similar to:
bfb6b98ed62a exclude vgem node and invalid drm node in vainfo
It's possible to have a vgem node at 128, and the VA-API node is at 129.
Signed-off-by: Brian Norris <briannorris@chromium.org>

test_va_api: Don't assume our DRM node is first

---

configure.ac
meson.build

This will help prevent erroneous linking to mixed versions of libva-xyz window system libraries that may not be binary compatible.  For example,
1. User installs libva-dev from distro packages that provides all libva-xyz.pc/.so window system libraries.
2. Then, user compiles and installs libva from source with 1 or more [auto] disabled libva-xyz window system libraries.
3. Finally, user compiles libva-utils from source, but configure finds a mix of distro installed and user compiled libva-xyz window system libraries and encounters linker error when not binary compatible with user installed libva.so.

libva-xyz should be same version as detected libva

---

encode/hevcencode.c

Set corresponding parameters in SPS etc. to the values from these 2 attributes, instead of hard-coding. If the attributes are not set, use default values which remains unchanged.
Why: The VAAPI hardware may have limits on SPS params, so there is 2 VA config attributes about this. With this commit the code will be more general.

[Encode] Add support for VAConfigAttribEncHEVCBlockSizes & VAConfigAttribEncHEVCFeatures

---

encode/h264encode.c

This the proposed fix foe encoding with larger gop. example idr_period 2048.

Fix for pic_order_cnt_lsb to accept larger GOP

---

encode/meson.build
videoprocess/meson.build

Closes: https://github.com/intel/libva-utils/issues/328
Tested inside the Mesa3D CI running on Debian 11 (bullseye). Build and runtime working perfectly with latest libva-utils with this MR.

meson: guard code introduced after libva 1.10 release

---

vainfo/vainfo.c

Adds vainfo support for printing `VAConfigAttribEncMaxTileRows` and `VAConfigAttribEncMaxTileCols`
Depends on https://github.com/intel/libva/pull/757
@dvrogozh @XinfengZhang

vainfo: Print VAConfigAttribEncMaxTileRows and VAConfigAttribEncMaxTileCols

---

encode/av1encode.c

1. Unify bitrate interface and remove buffer size related settings to
use driver default values for best quality.
2. Remove extra empty lines for refining code.
Signed-off-by: Xue, Maxim <maxim.xue@intel.com>

av1encode: simplify cbr/vbr interface and refine codes

---

videoprocess/vpp3dlut.cpp
videoprocess/vpphdr_tm.cpp

Signed-off-by: Alex1 Zhang alex1.zhang@intel.com

Fix VPP coverity issues

---

encode/av1encode.c
encode/avcenc.c
encode/hevcencode.c
encode/vp9enc.c

Fix some remaining encode coverity issues: 1 Unchecked return value; 1 Resource leak; 2 Modulo by zero
Signed-off-by: Chen, Bohan <bohan.chen@intel.com>

[Encode] Fix some coverity issues exposed in encode

---

.github/workflows/freebsd.yml

The previous v0 is not working anymore.
Update to use the latest v1 version.
same as https://github.com/intel/libva/pull/775
&https://github.com/intel/libva-utils/pull/352
but last one was closed unfortunately.

ci: update freebsd vm to the v1 version

---

test/test_va_api_query_config.cpp

VAAPI driver may support less profiles than specified in max_profiles. In this case, elements in profiles vector above the numProfiles have default value (0 or VAProfileMPEG2Simple) and test fails if this profile is not supported.

CheckEntrypointsForProfile test failed if MPEG2Simple is not suported

---

encode/h264encode.c

Freeing entrypoints before exit to fix a possible memory leak as pointed out in issue #182 
Signed-off-by: Shekhar Chauhan <shekhar.chauhan@intel.com>

Fixed memory leak

---

encode/hevcencode.c

update hevce fill header logic when VAConfigAttribEncHEVCFeatures
supported.

[HEVCe] update header logic

---

encode/av1encode.c

Fix some encode coverity issues: 2 Overflowed constant issues
Signed-off-by: Chen, Bosson [bosson.chen@intel.com](mailto:bosson.chen@intel.com)

[Encode] Fix coveirty overflowed issues
